# Set up everything for an AMORPH run
---

# Number of threads to use
num_threads: 4

# Data file for the run
data_file: "easy_data.txt"

# Which file of DNest4 options to use
dnest4_options_file: "OPTIONS_AGGRESSIVE"

# Section for things that affect the inference
inference_assumptions:

    # Control points
    control_points: [10.0, 40.0]

    # Maximum number of peaks
    max_num_narrow_peaks: 100
    max_num_wide_peaks: 100
