# Set up everything for an AMORPH run
---

# Number of threads to use
num_threads: 8

# Data file for the run
data_file: "easy_data.txt"

# Which file of DNest4 options to use
dnest4_options_file: "OPTIONS"

# Section for things that affect the inference
inference_assumptions:

    # Control points
    control_points: [10.0, 40.0]

    # Maximum number of peaks
    max_num_narrow_peaks: 100
    max_num_wide_peaks: 100

    # What subset of the domain should the amorphous peaks be allowed to
    # appear in? In these units, the domain goes from 0 to 1.
    left_edge: 0.3
    right_edge: 0.7

